version: 2.1

executors:
  macos-executor:
    macos:
      xcode: "14.2.0"
    resource_class: macos.m1.medium.gen1

jobs:
  test:
    executor: macos-executor
    steps:
      - checkout
      - run:
          name: Set up Python
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            source venv/bin/activate
            python install.py
            python llm.py


workflows:
  version: 2
  test-workflow:
    jobs:
      - test

